project:
  type: website

website:
  title: "GeospatialWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 01"
            href: Hands-On_Ex/Hands-On_Ex_01/Hands-On_Ex01.html
          - text: "Hands-on Exercise 02"
            href: Hands-On_Ex/Hands-On_Ex_02/Hands-On_Ex02.html
      - text: "In-class Exercise"
        menu: 
          - text: "In-Class Exercise 01"
            href: In-Class_Ex/In-Class_Ex_01/In-Class_Ex01.html
          - text: "In-Class Exercise 02"
            href: In-Class_Ex/In-Class_Ex_02/In-Class_Ex02.html
      - text: "Take-Home Exercise"
        menu:
          - text: "Take-Home Exercise 01"
            href: Take-Home_Ex/Take-Home_Ex_01/Take-Home_Ex01.html

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

