project:
  type: website

website:
  title: "GeospatialWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "In-class Exercise"
        menu: 
          - text: "In-Class Exercise 01"
            href: In-Class_Ex/In-Class_Ex_01/In-Class_Ex01.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

