---
title: "Hands-On Exercise 09"
author: "Henry Low"
date: "Sep 1 2024"
date-modified: "last-modified"
execute:
  evalu: true
  echo: true
  message: false
  freeze: true
format: html
editor: visual
---

# Data Sources

*(saved under 'data' folder)*

Four data sets will be used in this hands-on exercise, they are:

-   `MP14_SUBZONE_NO_SEA_PL`: URA Master Plan 2014 subzone boundary GIS data. This data set is downloaded from data.gov.sg.
-   `hexagons`: A 250m radius hexagons GIS data. This data set was created by using [*st_make_grid()*](https://r-spatial.github.io/sf/reference/st_make_grid.html) of sf package. It is in ESRI shapefile format.
-   `ELDERCARE`: GIS data showing location of eldercare service. [This data](https://data.gov.sg/dataset/eldercare-services) is downloaded from data.gov.sg. There are two versions. One in ESRI shapefile format. The other one in Google kml file format. For the purpose of this hands-on exercise, ESRI shapefile format is provided.
-   `OD_Matrix`: a distance matrix in csv format. There are six fields in the data file. They are:
    -   `origin_id`: the unique id values of the origin (i.e. `fid` of hexagon data set.),
    -   `destination_id`: the unique id values of the destination (i.e. `fid` of `ELDERCARE` data set.),
    -   `entry_cost`: the perpendicular distance between the origins and the nearest road),
    -   `network_cost`: the actual network distance from the origin and destination,
    -   `exit_cost`: the perpendicular distance between the destination and the nearest road), and
    -   `total_cost`: the summation of `entry_cost`, `network_cost` and `exit_cost`.

# Chapter 17: **Modelling Geographical Accessibility**

## 17.1 Setting Up

The goal of this exercise is to:

-   to import GIS polygon data into R and save them as simple feature data frame by using appropriate functions of sf package of R;
-   to import aspatial data into R and save them as simple feature data frame by using appropriate functions of sf package of R;
-   to computer accessibility measure by using Hansen’s potential model and Spatial Accessibility Measure (SAM); and
-   to visualise the accessibility measures by using tmap and ggplot2 packages.

### 17.1.1 Loading the R packages

\-`sf` package to perform geospatial wrangling tasks \
-`SpatialAcc` package to model geographical accessibility tasks \
- `ggstatsplot` package for statistical analysis \
- `tmap` and `ggplot2` package for plotting tasks \
-`tidyverse` and `reshape2` package for reading csv files, dataframe processing tasks 

```{r}
pacman::p_load(tmap, SpatialAcc, sf, 
               ggstatsplot, reshape2,
               tidyverse)
```

### 
